/*
 * Cmd.cs
 * 
 * Base class for commands. Derive your command from this class and
 * add it to the _commands array in class Program, and you'll be able to 
 * call it from the command line.
 *  
 * MIT License (see: LICENSE)
 * Copyright (c) 2021 Tomaz Stih
 * 
 * 02.03.2021   tstih
 * 
 */
using System.Text;

namespace Idp.Gpx.Common.CmdLine {

    public abstract class Cmd {

        #region Overridable(s)
        /// <summary>
        /// Name of your command. You will use this on command line as first argument.
        /// </summary>
        public abstract string Name { get; }

        /// <summary>
        /// Description of your command. This will be used in autogenerated help.
        /// </summary>
        public abstract string Desc { get; }

        /// <summary>
        /// Execute the command. The main calls this function and returns 
        /// </summary>
        /// <param name="std">Standard output.</param>
        /// <param name="err">Output for errors.</param>
        /// <returns>0 for success, otherwise error code that will be returned by the console application</returns>
        public abstract int Execute(StringBuilder std, StringBuilder err);
        #endregion // Overridable(s)

    }
}